export { default as DefaultSection } from './default-section/DefaultSection'
export { default as HeroSection } from './hero-section/HeroSection'
export { default as ImageSection } from './image-section/ImageSection'
export { default as IntroSection } from './intro-section/IntroSection'
export { default as NotificationSection } from './notification-section/NotificationSection'
export { default as VideoSection } from './video-section/VideoSection'
