export { default as Forms } from './Forms'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as DetailPost } from './Posts/DetailPost'
export { default as Posts } from './Posts'
